//layout.jsは全ての土台であり、アプリケーション全体を包む役割を果たします。
//このファイル「layout.jsは"必ずServer Componentを保つ"」
import { Open_Sans } from 'next/font/google';
import { Noto_Sans_JP } from 'next/font/google';

import StyledComponentsRegistry from './lib/styled-components-registry';
import './globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

//Google Fontの設定(variableを使うのは複数フォントを使う場合に便利)
const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'], ////ラテン文字をサブセットとして設定
});

const notoSans = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next Gallery Site',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body> */}
      <body className={`${openSans.variable} ${notoSans.variable} antialiased`}>
        <StyledComponentsRegistry>
          <Header />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
